site_name: Richard Shan - Fab Academy
nav:
  - Home: index.md
  - About: about.md
  - Documentation:
    - "Pre-Fab":
      - Pen Turning: lessons/prefab/pen.md
      - LED Glasses: lessons/prefab/glasses.md
      - TinyArcade: lessons/prefab/arcade.md
      - 3 Leaf Gyroscope Spinner: lessons/prefab/spinner.md
      - Cardboard Storage Box: lessons/prefab/box.md
      - RP2040: lessons/prefab/rp2040.md
    - "Week 1: Principles and Practices, Project Management":
      - GitLab & MKDocs: lessons/week1/gitlab.md
      - Final Project Brainstorming: lessons/week1/finalBrainstorming.md
      - Reflection: lessons/week1/reflection.md
    - "Week 2: Computer-Aided Design":
      - Exploring 3D CAD Programs: lessons/week2/cad.md
      - 2D Modelling: lessons/week2/2DModelling.md
      - Gravity Sketch: lessons/week2/gravitysketch.md

theme: readthedocs
highlightjs: true
